# Generated by Django 4.0.6 on 2022-08-02 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Proyectos',
        ),
    ]
