# Generated by Django 4.0.4 on 2022-08-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('app_prueba', '0002_delete_proyectos'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participantes',
            fields=[
                ('id', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('name', models.TextField(blank=True, null=True)),
                ('last_name', models.TextField(blank=True, null=True)),
                ('mail', models.TextField(blank=True, null=True)),
                ('team', models.TextField(blank=True, null=True)),
                ('proyect_id', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'participantes',
                'managed': False,
            },
        ),
    ]
