# Generated by Django 4.0.4 on 2022-08-09 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('project', models.CharField(max_length=100)),
            ],
        ),
    ]
