# Generated by Django 4.0.4 on 2022-08-09 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_prueba', '0004_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Contact',
        ),
    ]
