# Generated by Django 4.0.6 on 2022-08-02 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_alter_proyectos_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyectos',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='proyectos_imgs', verbose_name='Imagen'),
        ),
    ]
